# This is a basic workflow to help you get started with Actions

name: WenCaiMac

# Controls when the workflow will run
on:
  # push:
  schedule:
    - cron: '0 17 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm install

      # Runs a single command using the runners shell
      - name: Run script wencai
        run: node ./eco7/cn/quantW2.js
        
      - name: Push github
        run: |
          git config --global user.name 'oowuyue'
          git config --global user.email 'oowuyue@gmail.com'
          git config --global pull.rebase false
          git diff --exit-code ./eco7/ || (git add ./eco7/ && git commit -am "gitActWenCaiMacCommit" && git pull && git push)
